owner: brettinternet
repo: status

sites:
  - name: Blog
    url: https://brettinternet.com
  - name: Plex
    url: https://plex.brettgardiner.net
    expectedStatusCodes:
      - 200
      - 401
  - name: Bookmarks
    url: https://bookmarks.brettgardiner.net/u:brett

status-website:
  cname: status.brettinternet.com
  logoUrl: https://status.brettinternet.com/logo.svg
  favicon: https://status.brettinternet.com/favicon.ico
  name: Brett's Status Page
  introTitle: "Brett's service monitoring"
  introMessage: "Status page for [Brett](https://brettinternet)'s [homelab](https://github.com/brettinternet/homelab) services"
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
