owner: brettinternet
repo: status

sites:
  - name: Blog
    url: https://brettinternet.com
  - name: Plex
    url: https://plex.brettgardiner.net

status-website:
  cname: brettinternet.com
  logoUrl: https://raw.githubusercontent.com/brettinternet/brettinternet.github.io/blob/source/src/images/logo.svg
  favicon: https://brettinternet.com/favicon.ico
  name: Status
  introTitle: "Brett's service monitoring"
  introMessage: "Status page for [Brett](https://brettinternet)'s homelab services"
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
